sudo: required
service:
  - docker

before_install:
  - docker build -t dacozai/my-docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dacozai/my-docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "my-docker-react"
  env: "MyDockerReact-env" 
  bucket_name: "elasticbeanstalk-us-east-2-709117190578"
  bucket_path: "my-docker-react" 
  on:
    branch: master

access_key_id: $AWS_ACCESS_KEY
secret_access_key: $AWS_SECRET_KEY


